---
#setup_remote_docker_defaults: &setup_remote_docker_defaults
  # This is pinned to 19 to resolve a problem described here:
  # https://discuss.circleci.com/t/docker-build-fails-with-nonsensical-eperm-operation-not-permitted-copyfile/37364/24
#  version: 19.03.13

version: 2.1
jobs:
  # release_docker will build and push the Docker image.
  release_docker:
    machine:
      # image: ubuntu-2204:2024.05.1
      image: ubuntu-2204:2024.11.1
    #resource_class: arm.medium
    resource_class: arm.large
    # not effective
    #environment:
    #  WEBPACK_MAX_CORES: "2"
    #  NODE_OPTIONS: "--max-old-space-size=4096"
    steps:
      - checkout
      - run:
          name: Get branch name of latest release from official repo
          command: |
            # 2023-Feb 7.4.7 did not add the v in front of the version
            # 2023-Mar v7.4.8 they add back the v
            # for tag v.a.b.c, use: sort -r -V
            # for tag a.b.c, use sort -r -h
            curl -sL https://api.github.com/repos/coralproject/talk/releases | \
              jq -r ".[].tag_name" | grep -v rc | sort -r -V | head -n 1 > /tmp/latest-branch-name
            echo "REMOTE_BRANCH_NAME=$(cat /tmp/latest-branch-name)" >> $BASH_ENV
            cat /tmp/latest-branch-name
            echo ${REMOTE_BRANCH_NAME}
      - run:
          name: CheckOut application code from Git to build
          command:
            git clone -b ${REMOTE_BRANCH_NAME} --single-branch https://github.com/coralproject/talk
      - run:
          name: Get commit hash
          working_directory: talk
          command: |
            echo "COMMIT_HASH=$(git log --pretty=format:'%h' -n 1)" >> $BASH_ENV
      - run:
          name: Build container
          working_directory: talk
          command: |
            echo ${COMMIT_HASH}
            pwd
            ls -la ..
            ls -la .
            echo "$GITLAB_TOKEN" | docker login --username "$GITLAB_USERNAME" --password-stdin registry.gitlab.com
            # To use squash, the daemon needs to enable experimental feature
            sudo bash -c 'echo "{\"experimental\": true}" > /etc/docker/daemon.json'
            sudo systemctl restart docker
            DOCKER_CLI_EXPERIMENTAL=enabled docker build --squash \
              -t registry.gitlab.com/patrickdung/docker-images/${CIRCLE_PROJECT_REPONAME}:${REMOTE_BRANCH_NAME} \
              --build-arg REVISION_HASH=${COMMIT_HASH} \
              --build-arg LABEL_IMAGE_URL=https://github.com/coralproject/talk \
              --build-arg LABEL_IMAGE_SOURCE=${CIRCLE_REPOSITORY_URL} \
               -f ../Dockerfile .
            docker push registry.gitlab.com/patrickdung/docker-images/${CIRCLE_PROJECT_REPONAME}:${REMOTE_BRANCH_NAME}
          no_output_timeout: 30m
      - run:
          name: Trigger GH action
          command: |
            curl -X POST -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${GITHUB_DISPATCH_TOKEN}" \
            https://api.github.com/repos/patrickdung/${CIRCLE_PROJECT_REPONAME}/dispatches \
            -d '{"event_type":"build_container_completed"}'

# filter_release will add the filters for a deploy job in a workflow to make it
# only execute on a deploy related job.
filter_release: &filter_release
  filters:
    branches:
      only:
        - main
    tags:
      only: /^v.*/

# filter_tagged_release will add the filters for a deploy job in a workflow to
# make it only execute on a tagged release.
filter_tagged_release: &filter_tagged_release
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^v.*/

# filter_develop will add the filters for a development related commit.
filter_develop: &filter_develop
  filters:
    branches:
      ignore:
        - main

workflows:
  build-test-deploy:
    jobs:
      - release_docker:
          <<: *filter_release
