---
#setup_remote_docker_defaults: &setup_remote_docker_defaults
  # This is pinned to 19 to resolve a problem described here:
  # https://discuss.circleci.com/t/docker-build-fails-with-nonsensical-eperm-operation-not-permitted-copyfile/37364/24
#  version: 19.03.13

version: 2.1
jobs:
  # release_docker will build and push the Docker image.
  release_docker:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Get branch name of latest release from official repo
          command: |
            curl -sL https://api.github.com/repos/coralproject/talk/releases | \
              jq -r ".[].tag_name" | grep -v rc | sort -nr -t. -k 1 -k 2 -k 3 | head -n 1 > /tmp/latest-branch-name
            echo "REMOTE_BRANCH_NAME=$(cat /tmp/latest-branch-name)" >> $BASH_ENV
            cat /tmp/latest-branch-name
            echo ${REMOTE_BRANCH_NAME}
      - run:
          name: CheckOut application code from Git to build
          command:
            git clone -b ${REMOTE_BRANCH_NAME} --single-branch https://github.com/coralproject/talk
      - run:
          name: Get commit hash
          working_directory: talk
          command: |
            echo "COMMIT_HASH=$(git log --pretty=format:'%h' -n 1)" >> $BASH_ENV
      - deploy:
          name: Build container
          working_directory: talk
          command: |
            echo ${COMMIT_HASH}
            pwd
            ls -la ..
            ls -la .
            echo "$GITLAB_PASSWORD" | docker login --username "$GITLAB_TOKEN" --password-stdin registry.gitlab.com
            # To use squash, the daemon needs to enable experimental feature
            sudo bash -c 'echo "{\"experimental\": true}" > /etc/docker/daemon.json'
            sudo systemctl restart docker
            DOCKER_CLI_EXPERIMENTAL=enabled docker build --squash \
              -t registry.gitlab.com/patrickdung/docker-images$/${CIRCLE_PROJECT_REPONAME}:${REMOTE_BRANCH_NAME} \
              --build-arg REVISION_HASH=${COMMIT_HASH} \
              --build-arg LABEL_IMAGE_URL=https://github.com/coralproject/talk \
              --build-arg LABEL_IMAGE_SOURCE=${CIRCLE_REPOSITORY_URL} \
               -f ../Dockerfile .
            docker push registry.gitlab.com/patrickdung/docker-images/${CIRCLE_PROJECT_REPONAME}:${REMOTE_BRANCH_NAME}
          no_output_timeout: 30m

# filter_release will add the filters for a deploy job in a workflow to make it
# only execute on a deploy related job.
filter_release: &filter_release
  filters:
    branches:
      only:
        - main
    tags:
      only: /^v.*/

# filter_tagged_release will add the filters for a deploy job in a workflow to
# make it only execute on a tagged release.
filter_tagged_release: &filter_tagged_release
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^v.*/

# filter_develop will add the filters for a development related commit.
filter_develop: &filter_develop
  filters:
    branches:
      ignore:
        - main

workflows:
  build-test-deploy:
    jobs:
      - release_docker:
          <<: *filter_release
